version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/our_trip'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
      - chrome
    links:
      - db
    networks:
      - backend
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
        - gateway: 172.18.0.1
