version: '3'

volumes: 
  data-base:

services:
  our_trip:
    build: .
    ports: 
      - '3000:3000'
    volumes: 
      - '.:/our_trip'
    tty: true
    stdin_open: true
    environment:
      - 'DATABASE_PASSWORD=postgres'
    depends_on: db
    links: db
  
  db:
    image: postgres
    volumes: 'data-base:/var/lib/postgresql/data'