version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/our_trip'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
      - chrome
    links:
      - db
    networks:
      app_net:
        ipv4_address: 172.30.0.2
  db:
    image: postgres:12.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    networks:
      app_net:
        ipv4_address: 172.30.0.3
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
